### ISSUE TITLE
Redis support

### ISSUE THREAD

**Issue by carmas123** [ClusterWS/ClusterWS#35]
Do you have  intention, in the future, to make a Redis support?
I want to use ClusterWS for a large scale app with many connected clients and with thousands of channels. I think that is a good way to use a dedicated memory database to handle over 100k clients...or not?

**Comment by goriunov** [comment]
Yes we want to implement a way to use Redis instead of current Broker. This is  next version plans.

**Comment by goriunov** [comment]
We have implemented broker in a special way that it does not do a lot of work. Main thing is it gets and right away sends message to all servers which are listening. This way allows to reduce load of broker as it is a central process and respond for messaging across the system. Main load goes to each worker(server) and it is good because users are divided  across workers (server). So each Worker (server) responsible only for the clients which are connected to this particular worker(server) this allows to have high through put on broker and each server can handle thousands of user, and  i think you will be able to have 100k users even if you use our standard broker, it is mainly depends on cpu cores and ram of your machine. Redis in this case will make it a bit faster to communicate between processes, we are going to implement support for Redis and make it easy to connect and use with our system.

**Comment by carmas123** [comment]
Thank you so much for now...regards
