### ISSUE TITLE
Can you please expose WebSocket and WebSocketServer classes?

### ISSUE THREAD

**Issue by roblav96** [ClusterWS/ClusterWS#75]
### Submitting

- [ ] Bug
- [ ] Question
- [x] Suggestion
- [ ] Other

### Details

Few releases back I was able to `npm i clusterws` and import your incredible rewrite of `uws` implementation. Would you be willing to expose these rewrites or publish them to a separate package? Amazing work!

**Comment by goriunov** [comment]
I will look in to creating a separate package with `clusterws-uws` module to make it more accessible (will try to cover everything what uws offer except `http` ). Current version of `uws` should be accessible as `WebSocket ` and `WebSocketServer` from `clusterws` however it does not have all functionality as `uws` offer because module design specially for `clusterws` internal usage.

**Comment by goriunov** [comment]
Sorry, i have not exposed `WebSocket` and `WebSocketServer` in current version, i will look in to opening repository for `clusterws-uws` soon to make it as separate module.

**Comment by roblav96** [comment]
@goriunov Awesome! The only difference I've noticed is your custom serializer. Have you explored the use of [msgpack5](https://github.com/mcollina/msgpack5)? Just curious on your thoughts :D

**Comment by roblav96** [comment]
@goriunov Perfect =]

**Comment by goriunov** [comment]
@roblav96  i have pushed uWS to separate repo with and npm check out [ClusterWS-uWS](https://github.com/ClusterWS/ClusterWS-uWS)
